<?php
require_once 'init.php';

use Adianti\Database\TTransaction;
use PDO;

TTransaction::open('default');

try {
    $connection = TTransaction::get();

    // Criar tabela cidade_uf
    $sql = "CREATE TABLE IF NOT EXISTS cidade_uf (
        id  INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        uf   TEXT NOT NULL
    )";
    $connection->exec($sql);
    echo "✓ Tabela cidade_uf criada/verificada\n";

    // Limpar dados anteriores para evitar duplicatas
    $connection->exec("DELETE FROM cidade_uf");
    echo "✓ Dados anteriores removidos\n";

    $cidades = [
        // ── BRASIL ──────────────────────────────────────────────────────
        // Acre
        ['Rio Branco','AC'],
        ['Cruzeiro do Sul','AC'],
        // Alagoas
        ['Maceió','AL'],
        ['Arapiraca','AL'],
        ['Palmeira dos Índios','AL'],
        // Amapá
        ['Macapá','AP'],
        ['Santana','AP'],
        // Amazonas
        ['Manaus','AM'],
        ['Parintins','AM'],
        ['Itacoatiara','AM'],
        // Bahia
        ['Salvador','BA'],
        ['Feira de Santana','BA'],
        ['Vitória da Conquista','BA'],
        ['Camaçari','BA'],
        ['Juazeiro','BA'],
        ['Itabuna','BA'],
        ['Ilhéus','BA'],
        ['Barreiras','BA'],
        ['Jequié','BA'],
        ['Porto Seguro','BA'],
        // Ceará
        ['Fortaleza','CE'],
        ['Caucaia','CE'],
        ['Juazeiro do Norte','CE'],
        ['Maracanaú','CE'],
        ['Sobral','CE'],
        ['Crato','CE'],
        ['Itapipoca','CE'],
        // Distrito Federal
        ['Brasília','DF'],
        // Espírito Santo
        ['Vitória','ES'],
        ['Vila Velha','ES'],
        ['Cariacica','ES'],
        ['Serra','ES'],
        ['Cachoeiro de Itapemirim','ES'],
        ['Linhares','ES'],
        ['São Mateus','ES'],
        // Goiás
        ['Goiânia','GO'],
        ['Aparecida de Goiânia','GO'],
        ['Anápolis','GO'],
        ['Rio Verde','GO'],
        ['Luziânia','GO'],
        ['Águas Lindas de Goiás','GO'],
        ['Valparaíso de Goiás','GO'],
        ['Trindade','GO'],
        ['Formosa','GO'],
        ['Itumbiara','GO'],
        ['Catalão','GO'],
        // Maranhão
        ['São Luís','MA'],
        ['Imperatriz','MA'],
        ['São José de Ribamar','MA'],
        ['Timon','MA'],
        ['Caxias','MA'],
        ['Codó','MA'],
        ['Paço do Lumiar','MA'],
        // Mato Grosso
        ['Cuiabá','MT'],
        ['Várzea Grande','MT'],
        ['Rondonópolis','MT'],
        ['Sinop','MT'],
        ['Tangará da Serra','MT'],
        ['Cáceres','MT'],
        ['Sorriso','MT'],
        ['Lucas do Rio Verde','MT'],
        // Mato Grosso do Sul
        ['Campo Grande','MS'],
        ['Dourados','MS'],
        ['Três Lagoas','MS'],
        ['Corumbá','MS'],
        ['Ponta Porã','MS'],
        ['Naviraí','MS'],
        ['Nova Andradina','MS'],
        // Minas Gerais
        ['Belo Horizonte','MG'],
        ['Uberlândia','MG'],
        ['Contagem','MG'],
        ['Juiz de Fora','MG'],
        ['Betim','MG'],
        ['Montes Claros','MG'],
        ['Ribeirão das Neves','MG'],
        ['Uberaba','MG'],
        ['Governador Valadares','MG'],
        ['Ipatinga','MG'],
        ['Sete Lagoas','MG'],
        ['Divinópolis','MG'],
        ['Santa Luzia','MG'],
        ['Poços de Caldas','MG'],
        ['Patos de Minas','MG'],
        ['Pouso Alegre','MG'],
        ['Teófilo Otoni','MG'],
        ['Muriaé','MG'],
        ['Araguari','MG'],
        ['Itabira','MG'],
        ['Conselheiro Lafaiete','MG'],
        ['Varginha','MG'],
        ['Passos','MG'],
        ['Ituiutaba','MG'],
        // Pará
        ['Belém','PA'],
        ['Ananindeua','PA'],
        ['Marabá','PA'],
        ['Santarém','PA'],
        ['Castanhal','PA'],
        ['Parauapebas','PA'],
        ['Cametá','PA'],
        ['Altamira','PA'],
        // Paraíba
        ['João Pessoa','PB'],
        ['Campina Grande','PB'],
        ['Santa Rita','PB'],
        ['Patos','PB'],
        ['Bayeux','PB'],
        ['Sousa','PB'],
        // Paraná
        ['Curitiba','PR'],
        ['Londrina','PR'],
        ['Maringá','PR'],
        ['Ponta Grossa','PR'],
        ['Cascavel','PR'],
        ['São José dos Pinhais','PR'],
        ['Foz do Iguaçu','PR'],
        ['Colombo','PR'],
        ['Guarapuava','PR'],
        ['Paranaguá','PR'],
        ['Araucária','PR'],
        ['Toledo','PR'],
        ['Apucarana','PR'],
        ['Pinhais','PR'],
        ['Campo Largo','PR'],
        ['Arapongas','PR'],
        ['Umuarama','PR'],
        ['Francisco Beltrão','PR'],
        ['Pato Branco','PR'],
        ['Cianorte','PR'],
        // Pernambuco
        ['Recife','PE'],
        ['Caruaru','PE'],
        ['Olinda','PE'],
        ['Petrolina','PE'],
        ['Paulista','PE'],
        ['Cabo de Santo Agostinho','PE'],
        ['Jaboatão dos Guararapes','PE'],
        ['Garanhuns','PE'],
        ['Vitória de Santo Antão','PE'],
        ['Caruaru','PE'],
        // Piauí
        ['Teresina','PI'],
        ['Parnaíba','PI'],
        ['Picos','PI'],
        ['Piripiri','PI'],
        // Rio de Janeiro
        ['Rio de Janeiro','RJ'],
        ['São Gonçalo','RJ'],
        ['Duque de Caxias','RJ'],
        ['Nova Iguaçu','RJ'],
        ['Niterói','RJ'],
        ['Belford Roxo','RJ'],
        ['Campos dos Goytacazes','RJ'],
        ['São João de Meriti','RJ'],
        ['Petrópolis','RJ'],
        ['Volta Redonda','RJ'],
        ['Magé','RJ'],
        ['Itaboraí','RJ'],
        ['Angra dos Reis','RJ'],
        ['Nilópolis','RJ'],
        ['Maricá','RJ'],
        ['Resende','RJ'],
        ['Cabo Frio','RJ'],
        ['Nova Friburgo','RJ'],
        ['Barra Mansa','RJ'],
        ['Macaé','RJ'],
        // Rio Grande do Norte
        ['Natal','RN'],
        ['Mossoró','RN'],
        ['Parnamirim','RN'],
        ['São Gonçalo do Amarante','RN'],
        ['Caicó','RN'],
        // Rio Grande do Sul
        ['Porto Alegre','RS'],
        ['Caxias do Sul','RS'],
        ['Pelotas','RS'],
        ['Canoas','RS'],
        ['Santa Maria','RS'],
        ['Gravataí','RS'],
        ['Viamão','RS'],
        ['Novo Hamburgo','RS'],
        ['São Leopoldo','RS'],
        ['Rio Grande','RS'],
        ['Alvorada','RS'],
        ['Passo Fundo','RS'],
        ['Sapucaia do Sul','RS'],
        ['Uruguaiana','RS'],
        ['Santa Cruz do Sul','RS'],
        ['Cachoeirinha','RS'],
        ['Bagé','RS'],
        ['Bento Gonçalves','RS'],
        ['Erechim','RS'],
        ['Guaíba','RS'],
        ['Cachoeira do Sul','RS'],
        ['Santo Ângelo','RS'],
        ['Ijuí','RS'],
        ['Santana do Livramento','RS'],
        ['São Gabriel','RS'],
        ['Cruz Alta','RS'],
        ['Lajeado','RS'],
        ['Alegrete','RS'],
        ['Porto Xavier','RS'],
        ['São Borja','RS'],
        // Rondônia
        ['Porto Velho','RO'],
        ['Ji-Paraná','RO'],
        ['Ariquemes','RO'],
        ['Vilhena','RO'],
        ['Cacoal','RO'],
        // Roraima
        ['Boa Vista','RR'],
        // Santa Catarina
        ['Joinville','SC'],
        ['Florianópolis','SC'],
        ['Blumenau','SC'],
        ['São José','SC'],
        ['Criciúma','SC'],
        ['Chapecó','SC'],
        ['Itajaí','SC'],
        ['Jaraguá do Sul','SC'],
        ['Palhoça','SC'],
        ['Balneário Camboriú','SC'],
        ['Brusque','SC'],
        ['Caçador','SC'],
        ['Lages','SC'],
        ['Concórdia','SC'],
        ['Gaspar','SC'],
        ['Tubarão','SC'],
        ['São Bento do Sul','SC'],
        ['Araranguá','SC'],
        ['Camboriú','SC'],
        ['Navegantes','SC'],
        // São Paulo
        ['São Paulo','SP'],
        ['Guarulhos','SP'],
        ['Campinas','SP'],
        ['São Bernardo do Campo','SP'],
        ['Santo André','SP'],
        ['Osasco','SP'],
        ['São José dos Campos','SP'],
        ['Sorocaba','SP'],
        ['Mauá','SP'],
        ['São José do Rio Preto','SP'],
        ['Mogi das Cruzes','SP'],
        ['Ribeirão Preto','SP'],
        ['Jundiaí','SP'],
        ['Piracicaba','SP'],
        ['Bauru','SP'],
        ['São Vicente','SP'],
        ['Carapicuíba','SP'],
        ['Guarujá','SP'],
        ['Franca','SP'],
        ['Limeira','SP'],
        ['Taubaté','SP'],
        ['Santos','SP'],
        ['Diadema','SP'],
        ['Suzano','SP'],
        ['Praia Grande','SP'],
        ['São Carlos','SP'],
        ['Americana','SP'],
        ['Marília','SP'],
        ['Araraquara','SP'],
        ['Presidente Prudente','SP'],
        ['Indaiatuba','SP'],
        ['Cotia','SP'],
        ['Sumaré','SP'],
        ['Hortolândia','SP'],
        ['Barueri','SP'],
        ['Itaquaquecetuba','SP'],
        ['Taboão da Serra','SP'],
        ['Ferraz de Vasconcelos','SP'],
        ['Caçapava','SP'],
        ['Volta Redonda','SP'],
        ['Jacareí','SP'],
        ['Botucatu','SP'],
        ['São Roque','SP'],
        ['Araçatuba','SP'],
        ['Birigui','SP'],
        ['Assis','SP'],
        ['Ourinhos','SP'],
        ['Tupã','SP'],
        ['Barretos','SP'],
        ['Catanduva','SP'],
        ['Votuporanga','SP'],
        ['Itapeva','SP'],
        ['Itapetininga','SP'],
        ['Bragança Paulista','SP'],
        ['Atibaia','SP'],
        // Sergipe
        ['Aracaju','SE'],
        ['Lagarto','SE'],
        ['Itabaiana','SE'],
        ['Nossa Senhora do Socorro','SE'],
        // Tocantins
        ['Palmas','TO'],
        ['Araguaína','TO'],
        ['Gurupi','TO'],

        // ── ARGENTINA ───────────────────────────────────────────────────
        ['Buenos Aires','ARGENTINA'],
        ['Córdoba','ARGENTINA'],
        ['Rosario','ARGENTINA'],
        ['Mendoza','ARGENTINA'],
        ['La Plata','ARGENTINA'],
        ['San Miguel de Tucumán','ARGENTINA'],
        ['Mar del Plata','ARGENTINA'],
        ['Salta','ARGENTINA'],
        ['Santa Fe','ARGENTINA'],
        ['San Juan','ARGENTINA'],
        ['Posadas','ARGENTINA'],
        ['Corrientes','ARGENTINA'],
        ['Resistencia','ARGENTINA'],
        ['Neuquén','ARGENTINA'],
        ['Santiago del Estero','ARGENTINA'],
        ['Bahía Blanca','ARGENTINA'],
        ['San Salvador de Jujuy','ARGENTINA'],
        ['Paraná','ARGENTINA'],
        ['Formosa','ARGENTINA'],
        ['San Luis','ARGENTINA'],
        ['Río Cuarto','ARGENTINA'],
        ['Comodoro Rivadavia','ARGENTINA'],
        ['La Rioja','ARGENTINA'],
        ['Concordia','ARGENTINA'],
        ['Río Gallegos','ARGENTINA'],
        ['Ushuaia','ARGENTINA'],
        ['Puerto Madryn','ARGENTINA'],
        ['General Roca','ARGENTINA'],
        ['Puerto Iguazú','ARGENTINA'],
        ['Clorinda','ARGENTINA'],
        ['Paso de los Libres','ARGENTINA'],
        ['Santo Tomé','ARGENTINA'],
        ['Eldorado','ARGENTINA'],
        ['Oberá','ARGENTINA'],
        ['Goya','ARGENTINA'],
        ['San Rafael','ARGENTINA'],
        ['Zárate','ARGENTINA'],
        ['Campana','ARGENTINA'],
        ['Luján','ARGENTINA'],
        ['Santa Rosa','ARGENTINA'],
        ['Viedma','ARGENTINA'],
        ['San Carlos de Bariloche','ARGENTINA'],
        ['Trelew','ARGENTINA'],
        ['Rawson','ARGENTINA'],

        // ── CHILE ───────────────────────────────────────────────────────
        ['Santiago','CHILE'],
        ['Antofagasta','CHILE'],
        ['Valparaíso','CHILE'],
        ['Temuco','CHILE'],
        ['Rancagua','CHILE'],
        ['Concepción','CHILE'],
        ['Talca','CHILE'],
        ['Arica','CHILE'],
        ['Iquique','CHILE'],
        ['Puerto Montt','CHILE'],
        ['Chillán','CHILE'],
        ['Osorno','CHILE'],
        ['La Serena','CHILE'],
        ['Calama','CHILE'],
        ['Punta Arenas','CHILE'],
        ['Valdivia','CHILE'],
        ['Coquimbo','CHILE'],
        ['Copiapó','CHILE'],
        ['Curicó','CHILE'],
        ['Linares','CHILE'],
        ['Los Ángeles','CHILE'],
        ['Quilpué','CHILE'],
        ['Villa Alemana','CHILE'],
        ['San Antonio','CHILE'],
        ['Ovalle','CHILE'],
        ['Iquique','CHILE'],
        ['Tocopilla','CHILE'],
        ['Mejillones','CHILE'],
        ['Puerto Natales','CHILE'],
        ['Castro','CHILE'],
        ['Ancud','CHILE'],
        ['Puerto Varas','CHILE'],

        // ── URUGUAI ─────────────────────────────────────────────────────
        ['Montevidéu','URUGUAI'],
        ['Salto','URUGUAI'],
        ['Ciudad de la Costa','URUGUAI'],
        ['Paysandú','URUGUAI'],
        ['Las Piedras','URUGUAI'],
        ['Rivera','URUGUAI'],
        ['Maldonado','URUGUAI'],
        ['Tacuarembó','URUGUAI'],
        ['Melo','URUGUAI'],
        ['Durazno','URUGUAI'],
        ['Mercedes','URUGUAI'],
        ['Artigas','URUGUAI'],
        ['Treinta y Tres','URUGUAI'],
        ['Colonia del Sacramento','URUGUAI'],
        ['Rocha','URUGUAI'],
        ['Fray Bentos','URUGUAI'],
        ['San José de Mayo','URUGUAI'],
        ['Chuy','URUGUAI'],
        ['Minas','URUGUAI'],
        ['Trinidad','URUGUAI'],
        ['Punta del Este','URUGUAI'],
        ['Young','URUGUAI'],
        ['Bella Unión','URUGUAI'],
        ['Paso de los Toros','URUGUAI'],
        ['Canelones','URUGUAI'],

        // ── PARAGUAI ────────────────────────────────────────────────────
        ['Assunção','PARAGUAI'],
        ['Ciudad del Este','PARAGUAI'],
        ['San Lorenzo','PARAGUAI'],
        ['Luque','PARAGUAI'],
        ['Capiatá','PARAGUAI'],
        ['Lambaré','PARAGUAI'],
        ['Fernando de la Mora','PARAGUAI'],
        ['Limpio','PARAGUAI'],
        ['Ñemby','PARAGUAI'],
        ['Pedro Juan Caballero','PARAGUAI'],
        ['Encarnación','PARAGUAI'],
        ['Concepción','PARAGUAI'],
        ['Coronel Oviedo','PARAGUAI'],
        ['Presidente Franco','PARAGUAI'],
        ['Caaguazú','PARAGUAI'],
        ['Villarrica','PARAGUAI'],
        ['Caacupé','PARAGUAI'],
        ['Mariano Roque Alonso','PARAGUAI'],
        ['Hernandarias','PARAGUAI'],
        ['Paraguarí','PARAGUAI'],
        ['Pilar','PARAGUAI'],
        ['San Juan Bautista','PARAGUAI'],
        ['Salto del Guairá','PARAGUAI'],
        ['Ayolas','PARAGUAI'],
        ['San Estanislao','PARAGUAI'],
    ];

    $stmt = $connection->prepare("INSERT INTO cidade_uf (nome, uf) VALUES (?, ?)");
    $count = 0;
    foreach ($cidades as $c) {
        $stmt->execute([$c[0], $c[1]]);
        $count++;
    }

    echo "✓ {$count} cidades inseridas com sucesso\n";

    // Criar índice para buscas rápidas
    $connection->exec("CREATE INDEX IF NOT EXISTS idx_cidade_uf_uf ON cidade_uf (uf)");
    $connection->exec("CREATE INDEX IF NOT EXISTS idx_cidade_uf_nome ON cidade_uf (nome)");
    echo "✓ Índices criados\n";

    echo "\n✓ Tabela cidade_uf criada e populada com sucesso!\n";
    echo "  Exemplo de uso: SELECT nome || ',' || uf AS cidade_uf FROM cidade_uf ORDER BY uf, nome\n";

} catch (Exception $e) {
    echo "✗ Erro: " . $e->getMessage() . "\n";
    http_response_code(500);
}

TTransaction::close();
?>
